[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[pyupgrade]
args = ["--keep-runtime-typing", "--py38-plus"]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
plugins = "mypy_typing_asserts.mypy_plugin"

no_implicit_optional = true
implicit_reexport = false
strict_equality = true

warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

pretty = true
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true

[[tool.mypy.overrides]]
module = "jsf"
ignore_missing_imports = true
